### ISSUE TITLE
does not performance

### ISSUE THREAD

**Issue by Wellington07112014** [Sorrow446/MQ-DL#1]
When I try to run the application this error appears to me could you solve it?

MQ-DL.py  README.md  api  config.json  requirements.txt
$ python MQ-DL.py
Traceback (most recent call last):
  File "MQ-DL.py", line 31, in <module>
    os.chdir(os.path.dirname(__file__))
FileNotFoundError: [Errno 2] No such file or directory: ''
$

**Comment by Sorrow446** [comment]
This is the code that CDs into the same dir as the script so that it can read your config file. You can delete the four lines below and manually CD in instead.

```
if hasattr(sys, "frozen"):
	os.chdir(os.path.dirname(sys.executable))
else:
	os.chdir(os.path.dirname(__file__))
```

**Comment by Superhackman** [comment]
I have a question @Sorrow446 I missed something?
I want to know for what was the reason that you deleted your server from discord and almost all your repositories especially Qo-Dl reborn

**Comment by botezat** [comment]
Hello :) **Sorrow446**
![1](https://user-images.githubusercontent.com/50467655/80867229-ba33d500-8c9b-11ea-9b3f-eb3080250ec6.png)
