### ISSUE TITLE
Some item cannot be fetched in HR

### ISSUE THREAD

**Issue by tomty89** [Sorrow446/MQ-DL#10]
```
$ python MQ-DL.py -u https://content.mora-qualitas.com/artist/terence-lam/album/next-410946296/

 _____ _____     ____  __    
|     |     |___|    \|  |   
| | | |  |  |___|  |  |  |__ 
|_|_|_|__  _|   |____/|_____|
         |__|                
   
Signed in successfully.

Album 1 of 1:
Terence Lam - Next
Downloading track 1 of 1: Next - 24-bit / 48000 Hz FLAC
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.7M/27.7M [00:02<00:00, 11.5MB/s]
```

```
$ file mora/Terence\ Lam\ -\ Next/1.\ Next.flac 
mora/Terence Lam - Next/1. Next.flac: FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 12137852 samples
```

I suspect this happen when the site uses one "item" for both CD and HR files.

Thank you for the work btw. It allows me to at least have an extra source to cross-check my HR purchases on Qobuz for crap like UMG watermarking.

**Comment by Sorrow446** [comment]
Welcome. I'm failing to see what the issue is, sorry. Could you explain further?

**Comment by Sorrow446** [comment]
Just looked into this. The tool's not at fault; they've simply labelled a 16-bit track as 24.

**Comment by tomty89** [comment]
Yeah I added some `print()` to the code that realize that it's probably the case. Awful. :-(
Thanks anyway! :-D

**Comment by tomty89** [comment]
Btw, do you know if mora qualitas actually shares the same catalogue as Napster? (In other words, instead of the mora store.) It appears to me that mora qualitas also suffers from the UMG watermark issue. I didn't expect that to happen with Japanese providers. (So far only OTOTOY's catalogue seems clean. Haven't bothered to purchase affected albums from mora or recochoku.)

**Comment by Sorrow446** [comment]
I'm thinking so, but am not completely sure. You can see that every endpoint in my API wrapper belongs to Napster. https://github.com/Sorrow446/MQ-DL/blob/master/api/client.py

**Comment by tomty89** [comment]
Well at least I confirmed that the catalogue of the mora store is (as for now) different from the one of mora qualitas. Just purchased this on both mora and ototoy and downloaded from mora qualitas and qobuz:
https://mora.jp/package/43000006/00602507201623/
Only the checksums of the former two (raw tracks) are the same. So purchasing in Japan is still the only way to get original UMG tracks.
