### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by kpdean** [Sorrow446/MQ-DL#12]
Hi Sorrow ,
Is it still up? I am getting this error mess on this command
python3 MQ-DL.py -u https://mora.jp/package/43000002/ANTCD-A0000001648/ -q 4 -k -l ja-JP
 
Failed to login.
HTTPError: 400 Client Error: Bad Request for url: https://api.napster.com/oauth/token

thank you

**Comment by Slypser** [comment]
excuse me, how did you create the account, and with what bin?

**Comment by kpdean** [comment]
Crap I thought you can just run the program and get it going. I guess I cant use it now I require a log-in for it...

**Comment by Sorrow446** [comment]
Your subscription doesn't need to be active. Your account just has to have been subscribed at some point (free trial is fine). They accidentally allow you to grab any qualities after subscription expiry.

**Comment by EssentialistStoic** [comment]
Lol I tried to do same thing, but it's much more than that. Could not get past creating an account.

**Comment by Slypser** [comment]
It gives me this error
mq-dl.py: error: the following arguments are required: -u/--url
