### ISSUE TITLE
Bin MQ

### ISSUE THREAD

**Issue by Slypser** [Sorrow446/MQ-DL#13]
What kind of Bin do you use for MQ?  I'm testing with Bin from Tidal and crunchyrrol and it doesn't work for me.

**Comment by EssentialistStoic** [comment]
Did you find any way? Could not create a account.

**Comment by sorrowfan** [comment]
Mora-qualitas is Japan based company. So Tidal, crunchyrrol bin doesn't help

**Comment by sorrowfan** [comment]
> What kind of Bin do you use for MQ? I'm testing with Bin from Tidal and crunchyrrol and it doesn't work for me.

Mora-qualitas is Japan based company. So Tidal, crunchyrrol bin doesn't help
