### ISSUE TITLE
modification to enter application link and download individual songs ?    Thanks!!

### ISSUE THREAD

**Issue by adrianmejiam** [Sorrow446/MQ-DL#14]
![IMG_20200902_151844](https://user-images.githubusercontent.com/51228667/92032383-abcff580-ed2f-11ea-842b-15c2c4f9243c.jpg)

**Comment by Sorrow446** [comment]
Application URL? Windows & mobile app URLs are supported. Single tracks is quite a bit of work. Will think about it.

**Comment by adrianmejiam** [comment]
> Application URL? Windows & mobile app URLs are supported. Single tracks is quite a bit of work. Will think about it.

Nugs-DL Don't work any more ?.. congrats ✌️

**Comment by adrianmejiam** [comment]
![Screenshot_2020-09-04-16-17-30-285_com termux](https://user-images.githubusercontent.com/51228667/92285541-2df42180-eeca-11ea-96ef-6a95f3234dd5.jpg)


this is the link that is obtained from the application and it appears as invalid url..

Congrats... ✌️

**Comment by Sorrow446** [comment]
You have an old version. Download it again. I'm done with Nugs now, sorry. I archived it a long time ago.

**Comment by adrianmejiam** [comment]
Sorrow446. Thank you..!! ✌️

**Comment by EssentialistStoic** [comment]
How did you create a account, I tried many methods but could not create an account outside of Japan.

**Comment by sorrowfan** [comment]
@adrianmejiam leave your mail ID. I got something to ask you!

**Comment by adrianmejiam** [comment]
@sorrowfan 

https://www.facebook.com/groups/1448072245431374/?ref=share ✌️

**Comment by sorrowfan** [comment]
> How did you create a account, I tried many methods but could not create an account outside of Japan.

Same problem bro. Let see if someone help!

**Comment by 841466540** [comment]
> > 您是如何创建帐户的，我尝试了许多方法，但无法在日本境外创建帐户。
> 
> 同一个问题兄弟。让我们看看是否有人帮忙！

You can buy accounts directly. It's cheap

**Comment by adrianmejiam** [comment]
I have accounts available.. inbox

**Comment by Oleophobic** [comment]
> 
> 
> I have accounts available.. inbox

are they working accounts that can get tracks and what do you want in return?

**Comment by Oleophobic** [comment]
> 
> 
> > > 您是如何创建帐户的，我尝试了许多方法，但无法在日本境外创建帐户。
> > 
> > 
> > 同一个问题兄弟。让我们看看是否有人帮忙！
> 
> You can buy accounts directly. It's cheap

how can you show me, sorry im unaware of this method
