### ISSUE TITLE
Problem running MQ-DL windows app in cmd

### ISSUE THREAD

**Issue by sorrowfan** [Sorrow446/MQ-DL#15]
Thanks for making such a great tool. 
We can't take advantage of your tool since we don't have account with moraqualitas.
So all my request is to close this issue by updating atleast one trial moraqualitas account in comment or mail
Note: "moraqualitas doesn't accept other country people registration"

**Comment by Oleophobic** [comment]
> 
> 
> Thanks for making such a great tool.
> We can't take advantage of your tool since we don't have account with moraqualitas.
> So all my request is to close this issue by updating atleast one trial moraqualitas account in comment or mail
> Note: "moraqualitas doesn't accept other country people registration"

MQ-DL works fine in CMD this is not an issue with the code. The developer can not help you make an account.

**Comment by sorrowfan** [comment]
> > Thanks for making such a great tool.
> > We can't take advantage of your tool since we don't have account with moraqualitas.
> > So all my request is to close this issue by updating atleast one trial moraqualitas account in comment or mail
> > Note: "moraqualitas doesn't accept other country people registration"
> 
> MQ-DL works fine in CMD this is not an issue with the code. The developer can not make you an account.

So can you make a account for me. I tried many ways, but can't register........

**Comment by sorrowfan** [comment]
Have a look at the previous issue. Its not about tool, its about the account
