### ISSUE TITLE
api is DOWN...

### ISSUE THREAD

**Issue by godt2p4** [Sorrow446/MQ-DL#16]
I'm sorry to hear that below, and wondering if Sorrow446 will fix it.

Traceback (most recent call last):
  File "MQ-DL.py", line 294, in <module>
    main()
  File "MQ-DL.py", line 260, in main
    client.auth(cfg['email'], cfg['password'])
  File "/root/MQ-DL/morapy/morapy.py", line 70, in auth
    j = self.api_call(self.base + 'oauth/token', 'auth', email=email, pwd=pwd)
  File "/root/MQ-DL/morapy/morapy.py", line 63, in api_call
    raise AuthenticationError('Invalid credentials.')
morapy.exceptions.AuthenticationError: Invalid credentials.

{"code":"UnauthorizedError","message":"Unauthorized"}

**Comment by Sorrow446** [comment]
You're using the old first version before the rewrite. Download this git.

**Comment by godt2p4** [comment]
> You're using the old first version before the rewrite. Download this repo.

I see, thanks Sorrow.

BTW, how to add multiple url as it listed in the help?

**Comment by Sorrow446** [comment]
Pass them to the u arg separated by spaces.
`mq-dl.py -u (url1) (url2)`

Or from a text file:
`mq-dl.py -u G:\list.txt`

**Comment by godt2p4** [comment]
> Pass them to the u arg separated by spaces:
> `mq-dl.py -u (url1) (url2)`
> 
> Or from a text file:
> `mq-dl.py -u G:\list.txt`

Thanks, Sorrow.

It's quite useful and convenient.
