### ISSUE TITLE
Can't Figure out how to run executable.

### ISSUE THREAD

**Issue by ThePlayingGoblin** [Sorrow446/MQ-DL#19]
The original tool runs fine without issues, but the newer tool immediately terminates itself right after opening it. I don't know how to fix it, or what I have to do to run the program.

**Comment by Sorrow446** [comment]
See [this](https://github.com/Sorrow446/MQ-DL/issues/6#issuecomment-631921500). The rewrite is CLI-only. You could always write your own batch file.
