### ISSUE TITLE
Windows args issue.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/MQ-DL#2]
Not an issue with the tool itself, but having an ampersand in your URLs will break the args and cause the tool to use your config file values instead. It's a Windows console issue. The only fix is to remove before passing, or escape it.

`?type=web&cid=mqapp_share_web`

EDIT: you can also put all of your other args before your url arg to fix this.

**Comment by sorrowfan** [comment]
Do you know any credit card bin that works for Mora-qualitas trial premium account? I dont have valid payment information since iam outside of japan.

**Comment by sora444** [comment]
Can't loggin.
Failed to login.
HTTPError: 400 Client Error: Bad Request for url: https://api.napster.com/oauth/token
What should I do?

**Comment by Sorrow446** [comment]
> Can't loggin.
> Failed to login.
> HTTPError: 400 Client Error: Bad Request for url: https://api.napster.com/oauth/token
> What should I do?

I think they changed their API. I'll look into this tonight.

**Comment by Slypser** [comment]
the same thing happens to me too

**Comment by Slypser** [comment]
the same thing happens to me too

**Comment by Slypser** [comment]
It gives me this error
mq-dl.py: error: the following arguments are required: -u/--url

**Comment by Sorrow446** [comment]
It's still working fine here. When did you guys make your accounts?

**Comment by 841466540** [comment]
> 该工具本身不是问题，但您的URL中使用＆号将破坏args，并导致该工具改用您的配置文件值。这是Windows控制台问题。唯一的解决方法是在通过之前将其删除，或对其进行转义。
> 
> `?type=web&cid=mqapp_share_web`
> 
> 编辑：您还可以将所有其他args放在url arg之前以解决此问题。

How can I change the following content
