### ISSUE TITLE
Download by Artist

### ISSUE THREAD

**Issue by Leigo6677** [Sorrow446/MQ-DL#25]
Hi! this is my first time here, My question is can you download an artist's whole discography?

Thank you for providing us this tool!🎉

**Comment by Sorrow446** [comment]
Hello. Not currently, but I'll consider implementing it. You're welcome.

**Comment by Sorrow446** [comment]
Implemented in the [dev branch](https://github.com/Sorrow446/MQ-DL/tree/dev). It'll be pushed to master once it's fully tested and polished.

**Comment by Leigo6677** [comment]
Can i test this?

**Comment by Sorrow446** [comment]
Yep. Click the link above. There's only the source for it at the moment. No binaries.

**Comment by Leigo6677** [comment]
Yes I'm to try this and will provide feed back

**Comment by Leigo6677** [comment]
I already tried it works great. But it would be nice to have the albums / singles folder inside an artist folder.

**Comment by Leigo6677** [comment]
I already tried it. works great! But it would be nice to have the albums / singles folder inside an artist folder.

**Comment by Sorrow446** [comment]
> I already tried it. works great! But it would be nice to have the albums / singles folder inside an artist folder.

Just pushed a big update to src and Windows binary. See full patch notes and Windows binary [here](https://github.com/Sorrow446/MQ-DL/releases/tag/3).

You can configure your folder for each media type now. Nested folders aren't supported (yet), though.
