### ISSUE TITLE
Error downloading my "favorites" on Android

### ISSUE THREAD

**Issue by Loeacewave** [Sorrow446/MQ-DL#26]
![Screenshot_20210126-122737](https://user-images.githubusercontent.com/78039630/105880972-f6e5f000-5fd1-11eb-909d-35ccef43f725.png)

**Comment by Sorrow446** [comment]
Could you reply with the track's URL?

**Comment by Sorrow446** [comment]
Will look into.

**Comment by Loeacewave** [comment]
it is already working perfectly.  thanks!

**Comment by Sorrow446** [comment]
Great. Enjoy.
