### ISSUE TITLE
Error at line 381 & 188

### ISSUE THREAD

**Issue by wahyuside** [Sorrow446/MQ-DL#32]
I used google colab for run MQ-DL, and i found this error (my friend who uses this on android with termux also gets an error like this)
My input (! sign mean linux syntax in colab, & i save MQ-DL folder on /content/):
```
!python3 /content/MQ-DL/mq-dl.py -u https://content.mora-qualitas.com/?id=alb.203308770
```
and the result are:
```

 _____ _____     ____  __    
|     |     |___|    \|  |   
| | | |  |  |___|  |  |  |__ 
|_|_|_|__  _|   |____/|_____|
	 |__|                

Signed in successfully.

Item 1 of 1:
The Chainsmokers - Bouquet
Track 1 of 5:
Track failed.
Traceback (most recent call last):
  File "/content/MQ-DL/mq-dl.py", line 381, in iter_track
    track['id'])
  File "/content/MQ-DL/api/client.py", line 188, in get_tra_stream
    return j['streams'][0]['url']
IndexError: list index out of range
```

**Comment by Sorrow446** [comment]
This is because the account doesn't have an active subscription.

**Comment by wahyuside** [comment]
> This is because the account doesn't have an active subscription.

Okay, thx. Yes, the account doesn't have subscription since last night. Case closed
