### ISSUE TITLE
Login succeeded, but still can't download

### ISSUE THREAD

**Issue by 841466540** [Sorrow446/MQ-DL#38]
Signed in successfully.

Item 1 of 1:
Kaori Kobayashi - NOW and FOREVER
Track 1 of 13:
Track failed.
Traceback (most recent call last):
  File "mq-dl.py", line 381, in iter_track
    track['id'])
  File "api\client.py", line 188, in get_tra_stream
    'GET', 'v2.2/streams', params=params, headers=headers)
  File "api\client.py", line 21, in make_call
    r.raise_for_status()
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.napster.com/v2.2/streams?bitrate=96000&format=FLAC&protocol=&track=tra.555418711

Hello, is there something wrong with this agent?

**Comment by Sorrow446** [comment]
Dupe. https://github.com/Sorrow446/MQ-DL/issues/36

**Comment by 841466540** [comment]
> 欺骗。[＃36](https://github.com/Sorrow446/MQ-DL/issues/36)

How can I solve this problem?

**Comment by Sorrow446** [comment]
Fixed in the latest version.

**Comment by 841466540** [comment]
> 在最新版本中已修复。

have access to. Thank you very much for the tools
