### ISSUE TITLE
errors after config.sjon

### ISSUE THREAD

**Issue by Tecko71** [Sorrow446/MQ-DL#4]
After editing config.sjon I get read errors

Traceback (most recent call last):
  File "C:\OS\MQ-DL-master\MQ-DL.py", line 357, in <module>
    cfg = parse_prefs()
  File "C:\OS\MQ-DL-master\MQ-DL.py", line 71, in parse_prefs
    cfg = parse_cfg()
  File "C:\OS\MQ-DL-master\MQ-DL.py", line 64, in parse_cfg
    return json.load(f)
  File "C:\Users\tegha\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\tegha\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\tegha\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\tegha\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 22 (char 85)

**Comment by Sorrow446** [comment]
>   -o, --output-dir      Abs output directory. Double up backslashes or use
>                         single forward slashes for Windows. Default: \MQ-DL
>                         downloads

**Comment by Tecko71** [comment]
I do not get it to work I do something wrong in de config I use "C:\Users\Music" and my commendline:  "MQ-DL.py -u https://play.qobuz.com/album/b0cksdkfprljb -o C:\Users\Music" , i have windows

**Comment by Tecko71** [comment]
one step futher: 
 now failed to login and my credentials are right

usage: MQ-DL.py [-h] -u URL [URL ...] [-q {1,2,3,4}] [-c {1,2,3,4,5}] [-t TEMPLATE] [-k] [-o] [-l {en-US,ja-JP}]
MQ-DL.py: error: unrecognized arguments: [c:/Users/tegha/Music]

C:\OS\MQ-DL-master\MQ-DL-master>MQ-DL.py -u https://play.qobuz.com/album/b0cksdkfprljb [-o c:/Users/tegha/Music]

Failed to login.
HTTPError: 401 Client Error: Unauthorized for url: https://api.napster.com/oauth/token

**Comment by Sorrow446** [comment]
See line 34 of api/client.py. 			```
"Authorization": "Basic TlRFd05ESTFPR1V0WTJJeU1pMDBNR05tTFdJeE1qUXRZekkyT"
							 "WpWa1lXTTBPREpoOk56YzNPRE0yWWpVdE1XWTVNQzAwWWpVMkxXSm1P"
							 "RGN0TXpZd01UYzNOR0U1WkdFMQ==" 
```
This isn't account specific so it should work for everyone. You can get a new one by sniffing your login in browser. I see you've put in a Qobuz URL. This tool's not for Qobuz. Qo-DL is an archived project, which I won't be working on again ever.

**Comment by Tecko71** [comment]
Oh my mistake I thought it was for qobuz.

Op wo 20 mei 2020 om 14:57 schreef Sorrow446 <notifications@github.com>:
