### ISSUE TITLE
There is a bug here

### ISSUE THREAD

**Issue by ROOOCCCK** [Sorrow446/MQ-DL#40]
The individual songs in the album can not be downloaded, such as this picture, a total of 38 songs can only be downloaded 32 songs, アルバムのみ is not pull to the information, is it possible to fix?
![41231365](https://user-images.githubusercontent.com/79370772/108601070-9fbb1b80-73d5-11eb-89d8-9fc9828dc549.PNG)

**Comment by Sorrow446** [comment]
MQ-DL's for https://content.mora-qualitas.com/music/, not https://mora.jp/.

**Comment by zhangsenpei** [comment]
我知道，我是在M-Q软件中提取的链接，您可以看看，下载过程是这样子的
![2223123131](https://user-images.githubusercontent.com/79370772/108601380-3d631a80-73d7-11eb-892f-7f6fa7b27b8f.PNG)

**Comment by zhangsenpei** [comment]
I know, I extracted the link in the M-Q software, you can see, the download process is like this
![2223123131](https://user-images.githubusercontent.com/79370772/108601450-9a5ed080-73d7-11eb-9d88-0db8e3868a6e.PNG)

**Comment by zhangsenpei** [comment]
The copyright information is sometimes missing from the downloaded files, and now the track number information doesn't exist either
![Uploading 33333333.PNG…]()

**Comment by zhangsenpei** [comment]
The copyright information is sometimes missing from the downloaded files, and now the track number information doesn't exist either
![33333333](https://user-images.githubusercontent.com/79370772/108601557-10fbce00-73d8-11eb-8269-edab1b8423e4.PNG)

**Comment by ROOOCCCK** [comment]
> MQ-DL's for https://content.mora-qualitas.com/music/, not https://mora.jp/.

I know, I extracted the link in the M-Q software, you can see, the download process is like this
![4444444455555](https://user-images.githubusercontent.com/79370772/108601692-c464c280-73d8-11eb-964d-ab48a271f7e5.PNG)



The copyright information is sometimes missing from the downloaded files, and now the track number information doesn't exist either
![33333333](https://user-images.githubusercontent.com/79370772/108601631-6cc65700-73d8-11eb-8cc7-e6e022fe5072.PNG)

**Comment by Sorrow446** [comment]
I can't do anything about the number of tracks, sorry. That's how many they provided for this album. 

Copyright tags are always written if mora provides them. Track numbers are always written. Try something like mp3tag.
https://github.com/Sorrow446/MQ-DL/blob/master/mq-dl.py#L187

**Comment by ROOOCCCK** [comment]
> I can't do anything about the number of tracks, sorry. That's how many they provided for this album. 
> 
> Copyright tags are always written if mora provides them. Track numbers are always written. Try something like mp3tag.
> https://github.com/Sorrow446/MQ-DL/blob/master/mq-dl.py#L187

I've tried downloading the same album and the copyright information sometimes exists and sometimes disappears. Can't the tracks be resolved? I've tried to download the single link in mor-q with the album not downloaded, the software is unable to perform, which is not logical ah.

**Comment by ROOOCCCK** [comment]
> I can't do anything about the number of tracks, sorry. That's how many they provided for this album. 
> 
> Copyright tags are always written if mora provides them. Track numbers are always written. Try something like mp3tag.
> https://github.com/Sorrow446/MQ-DL/blob/master/mq-dl.py#L187

So I think there are bugs in the software, but unfortunately I don't know how to fix them 😂

**Comment by ROOOCCCK** [comment]
Now MJ's album, I compare, the player is 25 songs, can be downloaded normally, no problem. But Leehom Wang this album player has 28 songs, but only 25 can be downloaded, I tried to use the missing single link, is unable to download.

![5555555](https://user-images.githubusercontent.com/79370772/108615673-68825400-7441-11eb-9856-3915edc32894.PNG)

**Comment by Ganyu69** [comment]
> Now MJ's album, I compare, the player is 25 songs, can be downloaded normally, no problem. But Leehom Wang this album player has 28 songs, but only 25 can be downloaded, I tried to use the missing single link, is unable to download.
> 
> ![5555555](https://user-images.githubusercontent.com/79370772/108615673-68825400-7441-11eb-9856-3915edc32894.PNG)

![image](https://user-images.githubusercontent.com/78007658/108616827-bd26ce80-7443-11eb-886a-91e6f33cc53d.png)

look carefully

**Comment by ROOOCCCK** [comment]
> > Now MJ's album, I compare, the player is 25 songs, can be downloaded normally, no problem. But Leehom Wang this album player has 28 songs, but only 25 can be downloaded, I tried to use the missing single link, is unable to download.
> > 
> > ![5555555](https://user-images.githubusercontent.com/79370772/108615673-68825400-7441-11eb-9856-3915edc32894.PNG)
> 
> ![image](https://user-images.githubusercontent.com/78007658/108616827-bd26ce80-7443-11eb-886a-91e6f33cc53d.png)
> 
> look carefully

sorry😱
