### ISSUE TITLE
cannot launch MQ-DL_x86

### ISSUE THREAD

**Issue by 224mrv** [Sorrow446/MQ-DL#6]
Thanks for writing a great tool. But I tried downloading and the MQ-DL_x86 file automatically disappeared after opening

**Comment by Sorrow446** [comment]
That's normal behaviour. It's a CLI-only tool. Open up your console, and call it with your args. It'll use your config file as a fallback. No need to CD in beforehand.

Download a single album and use prefs from config file:
`G:\MQ-DL_x86.exe -u https://content.mora-qualitas.com/... `

Download two albums in FLAC and override config file quality pref:
`G:\MQ-DL_x86.exe -u https://content.mora-qualitas.com/... https://content.mora-qualitas.com/.. -q 4`

Download a single album and use prefs from config file:
`G:\MQ-DL_x86.exe -u https://content.mora-qualitas.com/... `

Download from txt file:
`G:\MQ-DL_x86.exe -u G:\\urls.txt `

Please also read [this](https://github.com/Sorrow446/MQ-DL/issues/2).

**Comment by 224mrv** [comment]
@Sorrow446 : I have used it very well with the previous tool (MQ-DL R1) however it only supports downloading with album only (that's okay). But I have reinstalled windows and cannot log in to the mora qualitas app on the window to get the download link due to the announcement of passing 3 devices.
But the current version makes me confused because I don't know how to fix args. Please help in detail. Thanks very much
![image](https://user-images.githubusercontent.com/57884616/82623427-5fdac400-9c0a-11ea-8714-f87099e2dd01.png)

**Comment by 224mrv** [comment]
@Sorrow446 : Does it only support album download links?

**Comment by Sorrow446** [comment]
Yep, sorry. It's quite a lot of effort to add support for single tracks / playlists.

**Comment by 841466540** [comment]
> 那是正常的行为。这是仅CLI的工具。打开控制台，并使用args进行调用。它将使用您的配置文件作为后备。无需预先放入CD。
> 
> 下载一个专辑并使用配置文件中的首选项：
> `G:\MQ-DL_x86.exe -u https://content.mora-qualitas.com/... `
> 
> 以最佳质量下载两张专辑，并覆盖配置文件质量偏好设置：
> `G:\MQ-DL_x86.exe -u https://content.mora-qualitas.com/... https://content.mora-qualitas.com/.. -q 4`
> 
> 从txt文件下载：
> `G:\MQ-DL_x86.exe -u G:\\urls.txt `
> 
> 还请阅读[此内容](https://github.com/Sorrow446/MQ-DL/issues/2)。
Thank you for your production. I run the code to show the following questions

Traceback (most recent call last):
  File "mq-dl.py", line 359, in <module>
  File "mq-dl.py", line 71, in parse_prefs
  File "mq-dl.py", line 63, in parse_cfg
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[15576] Failed to execute script mq-dl

And what command should I make to log in to my account

**Comment by Sorrow446** [comment]
You need to [download the config file](https://github.com/Sorrow446/MQ-DL/blob/master/config.json), then fill in your email and password.

**Comment by 841466540** [comment]
> 1. [下载配置文件](https://github.com/Sorrow446/MQ-DL/blob/master/config.json)。
> 2. 将其移动到MQ-DL目录。
> 3. 填写您的电子邮件和密码。

Yes, thank you for your guidance
