### ISSUE TITLE
Link compatibility

### ISSUE THREAD

**Issue by adrianmejiam** [Sorrow446/MQ-DL#7]
![IMG_20200521_125115](https://user-images.githubusercontent.com/51228667/82589467-d2dc3000-9b61-11ea-8a37-40a4b25d8e2a.jpg)
you can check the compatibility of the links

Listen to ウィズ・オア・ウィズアウト・ユー by U2 on mora qualitas: https://content.mora-qualitas.com/?id=tra.361763447

Regards

**Comment by Sorrow446** [comment]
Single tracks aren't supported (yet), sorry.
