### ISSUE TITLE
Download request cannot be issued because album title contains special characters

### ISSUE THREAD

**Issue by PerkinsChao** [Sorrow446/MQ-DL#8]
Hi, I really appreciated what you created, this is great!!!
But I find a problem when I use it that when album title and the sharing link contains special characters like "*", it can't be defined by your program, how can I avoid this problem and download the audio?
Here is an example: https://content.mora-qualitas.com/artist/413687078/album/-part2-**?type=web&cid=mqapp_share_web
美空ひばり入門 Part2 *ペイパー・ムーン* 美空ひばり

**Comment by Sorrow446** [comment]
You're welcome. Thank you. Will look into this tonight.

**Comment by Sorrow446** [comment]
Fixed, sorry about that.

**Comment by PerkinsChao** [comment]
Thank you so much, but I'm really bad at python, so I hope you can pack a *.exe file if it's convenient for you

**Comment by Sorrow446** [comment]
No problem. Can do tomorrow.

**Comment by Sorrow446** [comment]
Here you go: https://github.com/Sorrow446/MQ-DL/releases/download/R2/MQ-DL_x86.exe
