### ISSUE TITLE
not work when url is alb.xxxxxxxx

### ISSUE THREAD

**Issue by littlealone100** [Sorrow446/MQ-DL#9]
the same album

this url work
https://content.mora-qualitas.com/artist/yumi-matsutoya/album/dawn-purple-remastered-2019

this url not work, can't download, meet HTTP Error
https://content.mora-qualitas.com/artist/yumi-matsutoya/album/alb.406030712

I also want to know how to get an album's url like the first url? When I share albums from app, it only show url like https://content.mora-qualitas.com/?id=alb.406030712

**Comment by littlealone100** [comment]
I also want to know how to get an album's url like the first url? When I share albums from app, it only show url like alb.xxxxxx

**Comment by littlealone100** [comment]
Due to when I share albums from app, it only show url like alb.xxxxxx.....  I change the main.py...

```
def check_url(url):
	regex = (
#		r'https://content.mora-qualitas.com/artist/([a-zA-Z-\d]+)/album/'
#		r'(alb.\d{9}|[a-zA-Z-\d*]+)(?:/track/(t.\d{9}|[a-zA-Z=\d]+))?'
		r'https://content.mora-qualitas.com/\?id='
		r'(alb.\d{9})'
	)
	m = re.match(regex, url)
	return m.group(1)

```


```
if __name__ == "__main__":
	title()
	cfg = parse_prefs()
	auth()
	total = len(cfg['url'])
	for num, url in enumerate(cfg['url'], 1):
		print("\nAlbum {} of {}:".format(num, total))
		try:
#			alb_art, alb_id, tra_id = check_url(url)
			alb_id = check_url(url)
		except AttributeError:
			print("Invalid url:", url)
			continue
#		alb_id = client.resolve_id(alb_art, alb_id)
		try:
			main(alb_id)
		except Exception as e:
			print("Album failed.")
			err(e)
```

**Comment by littlealone100** [comment]
> 
> Fixed. The vars were named wrongly and the client's resolve function was being called instead of the main script's one.
> 
> The first two URLs are from the Windows app. Never seen this before: `?id=alb.406030712`.

I get url  ?id=alb.xxxxxx  from Android app

**Comment by Sorrow446** [comment]
Would require a regex tweak. Will do this in the future. For now you'll have to manually convert them.

**Comment by littlealone100** [comment]
I tried lastest code. It still not work...

**Comment by 224mrv** [comment]
![image](https://user-images.githubusercontent.com/57884616/84562855-8ca17780-ad81-11ea-9e88-b457c4891034.png)
I tried with androi app shared link ?id=alb.xxxxx and it didn't work for me. is it work for everyone ?

**Comment by Sorrow446** [comment]
It's not pushed to the Windows build yet.

**Comment by sorrowfan** [comment]
i have mq account but i have not added payment information nor completed signup. when i use that details in config.json. It shows signedin successfully which means i can download right?

**Comment by Sorrow446** [comment]
The script doesn't have any subscription-checking code, so it'll run. Their API won't return any track streams to you, though. You must have had a subscription at some point (trial will also work).
